/*
 * Author: (C) Samuel Lenk
 * Project: SQL with PostgreSQL
 * Web: https://linux-trainings.de
 * Purpose: use the DEFAULT constraint
 */

-- let's create a table for customer with some DEFAULT values
create table customer (
	id int not null generated by default as identity,
	first_name varchar not null,
	last_name varchar,
	email varchar,
	active bool default true,
	country text default 'US'
);

-- see how other than the provided fields are filled
insert into customer (first_name, email) values ('Jenny', 'jenny@abc.de');
-- but we also explicitly provide something else
insert into customer (first_name, email, active) values ('Jenny', 'jenny@abc.de', false);
insert into customer (first_name, email, country) values ('Jenny', 'jenny@abc.de','CA');

-- check the result
select * from customer;

